### ISSUE TITLE
Build Fail

### ISSUE THREAD

**Issue by redknight1056** [sat8/yocto-tinkerboard#2]
Hello.

While I can build the native rockchip yocto build, I find it a bit lacking in terms of SSH etc.

I tried to build via your image but get the following issues:
`WARNING: /home/ben/yocto-tinkerboard-master/sources/meta-rockchip/recipes-kernel/linux/linux-rockchip_4.4.bb: Exception during build_dependencies for do_kernel_checkout
WARNING: /home/ben/yocto-tinkerboard-master/sources/meta-rockchip/recipes-kernel/linux/linux-rockchip_4.4.bb: Error during finalise of /home/ben/yocto-tinkerboard-master/sources/meta-rockchip/recipes-kernel/linux/linux-rockchip_4.4.bb
ERROR: ExpansionError during parsing /home/ben/yocto-tinkerboard-master/sources/meta-rockchip/recipes-multimedia/gstreamer/gstreamer1.0-rockchip_git.bb
Traceback (most recent call last):
  File "/home/ben/yocto-tinkerboard-master/sources/poky/bitbake/lib/bb/data_smart.py", line 386, in DataSmart.expandWithRefs(s='develop++git${SRCPV}', varname='PV'):
                 try:
    >                s = __expand_var_regexp__.sub(varparse.var_sub, s)
                     try:
  File "/home/ben/yocto-tinkerboard-master/sources/poky/bitbake/lib/bb/data_smart.py", line 111, in VariableParse.var_sub(match=<_sre.SRE_Match object; span=(12, 20), match='${SRCPV}'>):
                 else:
    >                var = self.d.getVarFlag(key, "_content", True)
                 self.references.add(key)
  File "/home/ben/yocto-tinkerboard-master/sources/poky/bitbake/lib/bb/data_smart.py", line 737, in DataSmart.getVarFlag(var='SRCPV', flag='_content', expand=True, noweakdefault=False, parsing=False):
                     cachename = var + "[" + flag + "]"
    >            value = self.expand(value, cachename)
     
  File "/home/ben/yocto-tinkerboard-master/sources/poky/bitbake/lib/bb/data_smart.py", line 410, in DataSmart.expand(s='${@bb.fetch2.get_srcrev(d)}', varname='SRCPV'):
         def expand(self, s, varname = None):
    >        return self.expandWithRefs(s, varname).value
     
  File "/home/ben/yocto-tinkerboard-master/sources/poky/bitbake/lib/bb/data_smart.py", line 400, in DataSmart.expandWithRefs(s='${@bb.fetch2.get_srcrev(d)}', varname='SRCPV'):
                 except Exception as exc:
    >                raise ExpansionError(varname, s, exc) from exc
     
bb.data_smart.ExpansionError: Failure expanding variable SRCPV, expression was ${@bb.fetch2.get_srcrev(d)} which triggered exception FetchError: Fetcher failure: Fetch command export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus,guid=73b042492c422888b9fbcf1d59eaaba4"; export SSH_AGENT_PID="1087"; export SSH_AUTH_SOCK="/run/user/1000/keyring/ssh"; export PATH="/home/ben/yocto-tinkerboard-master/out/tmp/sysroots/x86_64-linux/usr/bin/python3-native:/home/ben/yocto-tinkerboard-master/sources/poky/scripts:/home/ben/yocto-tinkerboard-master/out/tmp/sysroots/x86_64-linux/usr/bin/arm-rk-linux-gnueabi:/home/ben/yocto-tinkerboard-master/out/tmp/sysroots/tinker-rk3288/usr/bin/crossscripts:/home/ben/yocto-tinkerboard-master/out/tmp/sysroots/x86_64-linux/usr/sbin:/home/ben/yocto-tinkerboard-master/out/tmp/sysroots/x86_64-linux/usr/bin:/home/ben/yocto-tinkerboard-master/out/tmp/sysroots/x86_64-linux/sbin:/home/ben/yocto-tinkerboard-master/out/tmp/sysroots/x86_64-linux/bin:/home/ben/yocto-tinkerboard-master/sources/poky/scripts:/home/ben/yocto-tinkerboard-master/sources/poky/bitbake/bin:/home/ben/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games"; export HOME="/home/ben"; git -c core.fsyncobjectfiles=0 ls-remote git://github.com/rockchip-linux/gstreamer-rockchip.git  failed with exit code 128, output:
fatal: Unable to look up github.com (port 9418) (Name or service not known)

Summary: There were 3 WARNING messages shown.
Summary: There was 1 ERROR message shown, returning a non-zero exit code.`

Also could I also ask the question that would it be possible to build a 'rk-none' version of your build with QT5 as I believe this setup would see the most use, with addition of the cross-complier. How would one achieve this?

System OS: Tried Ubuntu 16.04 and Debian 9. 2.1

**Comment by spedagadi** [comment]
@redknight1056 
I am trying a fresh build now. Not sure if anything has changed in rockchip repos. 
Regarding QT5, I shall spend some time this weekend. Hang on for an update..

**Comment by redknight1056** [comment]
Wow, that's certainly a fast response! I'm certainly very grateful for you to spend some of your weekend trying this.

Thank you.

**Comment by spedagadi** [comment]
@redknight1056 Here is an update:

The sources in this repo doesnot work anymore. there are a bunch of **failed to fetch** errors as rockchip repos references are not available anymore(rockchip team does this sometimes :) ) . To do this properly, I need to do a bit more work and reference the rockchip repos directly than to have separate copy that may not exist sometime in future.

These were fixed locally on my build pc and I checked that the image builds for **core-image-sato**. My changes to this repo are still to be merged (TODO). The second and perhaps the item of your interest is the QT5 build. There were two issues - 
* The amount of working RAM to build the image was small than what's expected. I did not have any swap space dedicated on my ubuntu pc (4GB physical RAM) and the build process halted on several occassions. This has been fixed now.
* I think the build process is pulling in QT5 examples/similar and somehow a compilation error occurs with 'main()' not defined etc., I need to investigate this further and fix this. (TODO)

FYI the link [here]http://rockchip.wikidot.com/yocto-user-guide-qt indicates rockchip's build process for QT.

**Comment by redknight1056** [comment]
@sat8 Thank you for doing some trials. It's abit of a pain that the rockchip team changed the file's.

Ya I have built the qt5-image but I have noticed they have done one update recently which when built gives you an unusable desktop with only 5 opinion's (settings,music, video and camera) with no method of accessing the terminal and no SSH. Pretty pointless. 

This is why, currently your build is the best choice, especially if you get Qt to working. I would like to bet that your updated image would be received well by the community.  

Once again thank you for your time.

**Comment by spedagadi** [comment]
@redknight1056 np. I think I got lucky after few iterations.  Initially, there were issues with swap space, then  package group and then my ubuntu PC automatically restarting due to the number of parallel make & bitbake threads being too high (these were ok for normal yocto build). I do have an image built but now I am trying once more to make sure the process is error free. Stay tuned ( I will perhaps create a new repo just so that this repo is not polluted..)

**Comment by redknight1056** [comment]
@sat8 ya my ubuntu machine restarted several things normally around the #2000 process of the build. Interesting discovery this issue is not seen on Debian 9 but is certainly there on Ubuntu 16.04.

**Comment by spedagadi** [comment]
@redknight1056 Can you try my new repo for QT @ https://github.com/sat8/tinkerboard-yocto-qt5-eglfs
Note that this is a console based image and when the board is connected to local network, you should be able to access it via SSH.

PS: For some reason, Rockchip team are not adding wifi fix to the mainline kernel. This repo uses the mainline kernel so it is most likely wifi will not work.

**Comment by redknight1056** [comment]
Ah amazing work @sat8. I'll try the build today. There are no issues from me with the lack of wireless :P

Just to ask the silly question but I take it  I'll be using the rockchip repo for building the cross-compiler using bitbake meta-toolchain-qt5 for 'rk-none'

**Comment by spedagadi** [comment]
@redknight1056 I have now updated the README.md in the repo with instructions on building the toolchain and configuring QTCreator. In Tinkerboard board forum [post](https://tinkerboarding.co.uk/forum/thread-63-post-2872.html#pid2872), I have provided a download link for pre-built image.

**Comment by redknight1056** [comment]
@sat8 super :P Thank you for your work and effort. I'm sure you have people certainly a lot of people help with your addition to the community.

While I'll be trying your build shortly I'll set this 'Issue' as solved.

Thank you once again.
